<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>{{database}}</title>
<!-- 
    generated by [toss](https://github.com/after12am/toss)
 -->
</head>
<body>
    <header>
        <h1>{{database}}</h1>
    </header>
    <section>
        {% for table in tablestatus %}
        <table>
            <tr>
                <th>Field</th>
                <th>Type</th>
                <th>Collation</th>
                <th>Null</th>
                <th>Key</th>
                <th>Default</th>
                <th>Extra</th>
                <th>Comment</th>
            </tr>
            {% for item in columns[table] %}
            <tr>
                <td>{{item[0]}}</td>
                <td>{{item[1]}}</td>
                <td>{{item[2]}}</td>
                <td>{{item[3]}}</td>
                <td>{{item[4]}}</td>
                <td>{{item[5]}}</td>
                <td>{{item[6]}}</td>
                <td>{{item[8]}}</td>
            </tr>
            {% endfor %}
        </table>
        {% endfor %}
    </section>
    <footer>
    </footer>
</body>
</html>